### ISSUE TITLE
Setup fails to find xml2-config on Windows

### ISSUE THREAD

**Issue by MaxAlex** [eomahony/Numberjack#48]
On Windows 7, Python 2.7, with lxml installed, I get the following error attempting to install numberjack via Pip;

```
C:\Python27\Scripts>pip install numberjack
Collecting numberjack
  Using cached Numberjack-1.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\max\appdata\local\temp\pip-build-pf0hnp\numberjack\setup.py", line 197, in <module>
        extra_compile_args=EXTRA_COMPILE_ARGS + xml2config('--cflags') +
      File "c:\users\max\appdata\local\temp\pip-build-pf0hnp\numberjack\setup.py", line 103, in xml2config
        raise RuntimeError("Could not find %s" % path)
    RuntimeError: Could not find xml2-config

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\max\appdata\loca\temp\pipbuild-pf0hnp\numberjack\
```

Any help or insight is appreciated.  Thanks!

**Comment by 9thbit** [comment]
Hi @MaxAlex, Windows is not officially supported, mainly because none of us use or have experience developing on Windows. An error like that is usually because the program is not available in the `PATH`. If you manage to get it working and needed some changes to Numberjack, we would welcome a pull-request. :)
