### ISSUE TITLE
ImportError: No module named '_Mistral'

### ISSUE THREAD

**Issue by Onejrussell-Zymergen** [eomahony/Numberjack#57]
When trying to use Numberjack as a dependency for a python package on mac os, I get the following below. I also get the same error in a python console when trying:
`import Numberjack.solvers.Mistral`

`Traceback (most recent call last):
  File "/opt/anaconda3/envs/env_test3/lib/python3.7/site-packages/Numberjack/solvers/Mistral.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_Mistral', [dirname(__file__)])
  File "/opt/anaconda3/envs/env_test3/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_Mistral'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/env_test3/lib/python3.7/site-packages/Numberjack/__init__.py", line 910, in load
    lib = __import__(solverstring, fromlist=[solverspkg])
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/opt/anaconda3/envs/env_test3/lib/python3.7/site-packages/Numberjack/solvers/Mistral.py", line 28, in <module>
    _Mistral = swig_import_helper()
  File "/opt/anaconda3/envs/env_test3/lib/python3.7/site-packages/Numberjack/solvers/Mistral.py", line 20, in swig_import_helper
    import _Mistral
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named '_Mistral'`

**Comment by Onejrussell-Zymergen** [comment]
when I try to compile from source on 10.14.3:
`python setup.py build -solver Mistral`

I get a bunch of warnings, then:
`clang: warning: libstdc++ is deprecated; move to libc++ [-Wdeprecated]
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
The following solvers could not be located on your system so their interface has been disabled: CPLEX, Gurobi, SCIP
Failed to build the following interfaces (details are above): Mistral`

**Comment by veghp** [comment]
I had a similar import error when installing with `pip`, but building the whole package from source, with 2 commands, as described in the [readme](https://github.com/eomahony/Numberjack#installation), solved the problem:
```
python setup.py build
python setup.py install
```
However, this was on Ubuntu.
